# Generated by Django 5.1.3 on 2024-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_price', models.IntegerField(blank=True, null=True)),
                ('pro_des', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_quantity', models.IntegerField(blank=True, null=True)),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='Product_Image')),
            ],
        ),
    ]
