# Generated by Django 5.1.3 on 2024-11-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='pro_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
