# Generated by Django 5.1.3 on 2024-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registerdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='cpwd',
            new_name='confirmpwd',
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
