# Generated by Django 5.1.3 on 2024-12-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_orderdb_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
